language: generic
dist: trusty
sudo: false

env:
  global:
    - GH_REPO_REF: github.com/bigclownlabs/bc-core-module-sdk.git
    - GH_REPO_NAME: bc-core-module-sdk
    - GH_PAGES_BRANCH: gh-pages
    - GH_PAGES_CNAME: sdk.bigclown.com
    - DOXYFILE: $TRAVIS_BUILD_DIR/Doxyfile
    - HTML_DIR: $TRAVIS_BUILD_DIR/doc/html

addons:
  apt:
    sources:
      - sourceline: 'ppa:team-gcc-arm-embedded/ppa'
    packages:
      - doxygen
      - graphviz
      - gcc-arm-embedded

script:
  - /bin/sh test-build-examples.sh

deploy:
  provider: script
  script:
    - /bin/sh deploy-doc.sh
  skip_cleanup: true
  on:
    branch: master
